src/overlays/ovl_menu/fox_option.c

Very small change, fixes #40.
Before:
After:

Display earned medals correctly in rankings menu

---

src/engine/fox_play.c
src/engine/fox_tank.c
src/overlays/ovl_i3/fox_aq.c
src/port/ui/ImguiUI.cpp

I made sure it works on the Arwing (Rails and  All Range Mode), Landmaster and the Blue Marine. 
Apparently the `Player_TankBoostBrake(player)` function in `fox_play.c` is only for Landmaster on All Range Mode, which doesn't exist in single-player. Since Multiplayer is not supported, I did not modify that function as I could not be sure it worked.

Add Infinite Boost cheat

---

include/sf64save.h

Ranking data created with PLANET_STATS() doesn't match data constructed with the PlanetStats struct, possibly due to a difference in endianness between platforms. I've elected to reorder the bits in PLANET_STATS() instead of the struct so that player-made rankings won't break.
Fixes #67 for new save files.

Reorder PLANET_STATS()

---

src/engine/fox_bg.c

Renames an instance of a variable that was missed when updating against decomp. I didn't find any other mistakes like this in f40105e.
Fixes #84.

Rename missed variable

---

src/engine/fox_play.c
src/engine/fox_tank.c
src/overlays/ovl_i3/fox_aq.c
src/port/hooks/Events.h
src/port/hooks/list/ActionEvent.h
src/port/mods/PortEnhancements.c

Still learning how to work with Hooks.

Player action hooks

---

src/engine/fox_play.c
src/engine/fox_tank.c
src/overlays/ovl_i3/fox_aq.c
src/port/ui/ImguiUI.cpp

Adds an option that inverts the Y-Axis in gameplay, without affecting menus and other parts where the player would use the control stick. Tested with all 3 vehicles, and both rails and 360.

Add option to invert Y axis

---

src/overlays/ovl_i1/fox_tr.c

Small change to get that number aligned properly in training mode.
Before:
After:

Align ring count to right edge

---

src/engine/fox_play.c
src/port/ui/ImguiUI.cpp
src/port/ui/ImguiUI.h

When a checkpoint is created via the Developer Menu, it now stores the info of what level it was created at, and checks that against `gCurrentLevel` upon trying to load a checkpoint.
Additionally, if a checkpoint is set, it now shows which level it is in.

Prevent loading checkpoints in the wrong level

---

src/engine/fox_play.c
src/engine/fox_tank.c
src/overlays/ovl_i3/fox_aq.c
src/port/hooks/list/EngineEvent.h
src/port/mods/PortEnhancements.c

Simply the same feature, but now in hooks form.
I also added a new pair of events, for PlayerUpdate.
We need this separate from GameUpdate to avoid crashes with access to the player in events that should happen every frame of gameplay specifically.
Second attempt at #113 due to git shenanigans

Move Infinite Boost to hooks system

---

src/engine/fox_effect.c
src/overlays/ovl_i3/fox_a6.c
src/port/ui/ImguiUI.cpp

I've seen more than one player mention in the Discord that the Gorgon's flashes hurts their eyes. 
And apparently the official VC version actually also removed those flashes.
To be clear, this is about the full-screen white flashes that happen when the Gorgon is firing its beam and when the Gorgon teleports.

Allow players to disable the Gorgon's screen flashes

---

src/engine/fox_play.c
src/port/mods/PortEnhancements.c

Adds a delay after firing a charged shot in Rapid Fire Mode (prevents an issue where a normal shot was fired in the same frame)
Uses L to shoot charged shots if `gLToCharge` is true

Bugfixes for Charged Shots in Rapid Fire mode

---

src/sys/sys_math.c

In the Title Screen there is a `while` loop that is true while two values are the same, and changes one of them via `RAND_INT`. 
`RAND_INT` uses the `Rand_ZeroOne` function internally. 
For reasons unknown to me, sometimes all 3 random seeds are set to zero even if `Rand_Init` was already executed. Since `Rand_ZeroOne` only changes the seed values through multiplication and division, the result is always zero in that case. This causes the Title Screen `while` loop to be stuck indefinitely. 
I made a bandaid fix by checking the `sRandSeed`s for equality to zero, and re-run `Rand_Init` if so.

Prevent getting locked down with unitialized random seed

---

src/engine/fox_display.c
src/engine/fox_hud.c
src/port/mods/PortEnhancements.c

Stop applying HUD Aspect Ratio to the black background of the death/restart screen
Apply HUD Aspect Ratio to "HELP!!" arrows, edge indicator arrows and the Beta Boost Gauge.

Fix HUD elements where HUD Aspect was applied wrong

---

src/engine/fox_display.c
src/port/ui/ImguiUI.cpp

The default value, which is the value used in vanilla, is 120. Here's a comparison between 120 and 60:

Allow customizing cockpit glass opacity

---

src/engine/fox_play.c

- Fixes taking damage through passive ticks on Solar level.
- Fixes taking damage with invuln cheat on Solar level through lava terrain collision.

Fix invuln cheat on Solar and terrain.

---

src/engine/fox_play.c
src/port/hooks/list/EngineEvent.h
src/port/mods/PortEnhancements.c
src/port/ui/ImguiUI.cpp

This lets you pause the game loop without having to show the pause menu, and also works in cutscenes. 
I was using this when trying to work out why the arwing cockpits seem to not be correctly attached (I haven't figured it out, but now we have a new debug thingy)

Add Debug Pause

---

src/engine/fox_hud.c
src/port/hooks/list/EngineEvent.h
src/port/mods/PortEnhancements.c
src/port/ui/ImguiUI.cpp

This increases visibility and is helpful for players with colorblindness. 
(It also looks much better with higher res texture packs)

Option to add outlines to ships in radar

---

src/port/mods/PortEnhancements.c
src/port/ui/ImguiUI.cpp

The checkbox now enables using the L button to toggle the debug pause. An additional checkbox also allows L to advance one frame from the paused state.

Improve Debug Pause; Add frame-advance

---

src/port/mods/PortEnhancements.c

It was a missing `RCP_SetupDL` call.

Bugfix: Outlines were causing the Wolfen radar icons to bug when a Supply crate was present

---

src/port/Engine.cpp
src/port/ui/ImguiUI.cpp

LUS defaults to always on now (if not set by the port). And this option was confusing for most users.
Might increase input latency by one frame, when V-Sync is on and FPS is even above the refresh rate for a moment. (Normal behavior with jitter fix on).

Remove jitter fix slider

---

src/port/Engine.cpp
src/port/ui/ImguiUI.cpp

https://github.com/HarbourMasters/Shipwright/pull/5132 ported to starship
- DirectX's "Match Refresh Rate" is now a checkbox like in OpenGL and Metal.
- Clamp max FPS to refresh rate when V-Sync is enabled or can't be disabled, regardless of the FPS sliders setting, to avoid slowdown in Metal / OpenGL and dropping frames in DirectX as much as possible.
- FPS slider allows up to 360 FPS in every renderer.
- More descriptive V-Sync tooltip
Also fixes GetInterpolationFPS() not being used to calculate desired FPS.

Unify FPS and V-Sync controls and behavior

---

src/port/Engine.cpp
src/port/ui/ImguiUI.cpp

https://github.com/HarbourMasters/Shipwright/pull/5132 ported to starship
- DirectX's "Match Refresh Rate" is now a checkbox like in OpenGL and Metal.
- Clamp max FPS to refresh rate when V-Sync is enabled or can't be disabled, regardless of the FPS sliders setting, to avoid slowdown in Metal / OpenGL and dropping frames in DirectX as much as possible.
- FPS slider allows up to 360 FPS in every renderer.
- More descriptive V-Sync tooltip
- **Changes Jitter Fix slider to a simple checkbox an renamed it to "Render parallelization"** (including the CVar)
Also fixes:
- GetInterpolationFPS() not being used to calculate desired FPS
- V-Sync checkbox not representing the default state (ON)

Unify FPS and V-Sync controls and behavior + Jitterfix change to Checkbox

---

README.md
src/port/Engine.cpp
src/port/ui/ImguiUI.cpp

I found that the shortcut for resetting (`CTRL`+`R`) was not actually being handled anywhere. I'm not sure if this is something that was handled elsewhere and was removed, but it seems like there's no way of handling combination key presses so I'm not sure how this would have been previously implemented.
This fixes #185 (at least for the reset, I'm not sure what the F9 shortcut is supposed to be) by changing the shortcut for resetting the game and handling that shortcut. I had a solution that used the existing `CTRL`+`R` shortcut but handling combination key presses was more complicated.
Feel free to close if this is better handled elsewhere.

Implement keyboard shortcut for reset

---

src/port/Engine.cpp

Noticed the file was still in the bundle for the appimage so figured it might just be loading it incorrectly, applied what 2ship does to handle its asset file and it worked.

Fixed starship.o2r load on Linux

---

src/port/ui/ImguiUI.cpp

The game would hang without closing if no ROM was selected. Now with this change it will exit the game like the error message suggests it should.

JP/EU ROM selection closes game if no ROM selected.

---

CMakeLists.txt
src/port/Engine.cpp
src/port/extractor/GameExtractor.cpp
src/port/resource/importers/ObjectInitFactory.cpp
src/port/resource/type/ObjectInit.cpp
src/port/resource/type/ObjectInit.h
src/port/ui/UIWidgets.cpp

See https://github.com/HarbourMasters/SpaghettiKart/pull/532 for info.

Fix non-portable
